services:
  - type: web
    name: tcm-exam-helper-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tcm-exam-db
          property: connectionString

databases:
  - name: tcm-exam-db
    databaseName: tcm_exam
    ipAllowList: [] 